CONFIG_NICE_VIEW_WIDGET_INVERTED=n

# YADS Screen Configuration
CONFIG_DONGLE_SCREEN_HORIZONTAL=y
CONFIG_DONGLE_SCREEN_FLIPPED=n
CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=80
CONFIG_DONGLE_SCREEN_MIN_BRIGHTNESS=10
CONFIG_DONGLE_SCREEN_DEFAULT_BRIGHTNESS=80
CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=300
CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
CONFIG_DONGLE_SCREEN_SYSTEM_ICON=2

# --- Power management for Prospector dongle ---
CONFIG_ZMK_IDLE_TIMEOUT=300000

# Enable full sleep support
CONFIG_ZMK_SLEEP=y

# After 15 minutes of inactivity, enter deep sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Make sure display exists and blanks when idle
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

CONFIG_ZMK_STUDIO_LOCKING=n
