manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: hitsmaxft
      url-base: https://github.com/hitsmaxft
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-dongle-screen-engine
      remote: hitsmaxft
      revision: v1.4.1
      path: modules/zmk-dongle-screen-engine
    - name: zdse-themes
      remote: hitsmaxft
      revision: main
      path: modules/zdse-themes
  self:
    path: config
